# Generated by Django 5.1 on 2024-09-21 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CentroColeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do centro de coleta.', max_length=255)),
                ('endereco', models.CharField(help_text='Endereço do centro de coleta.', max_length=500)),
                ('horario_funcionamento', models.CharField(help_text='Horário de funcionamento.', max_length=100)),
            ],
        ),
    ]
