# Generated by Django 5.1 on 2024-09-21 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('centros', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='centrocoleta',
            name='telefone',
            field=models.ForeignKey(help_text='Telefone do centro.', on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
        migrations.AddField(
            model_name='centrocoleta',
            name='usuario_responsavel',
            field=models.ForeignKey(help_text='Usuário responsável pelo centro.', on_delete=django.db.models.deletion.CASCADE, related_name='centros_responsaveis', to='users.user'),
        ),
    ]
